### ISSUE TITLE
--rootGenomeLength doesn't work on phastSim 0.0.3

### ISSUE THREAD

**Issue by trongnhanuit** [NicolaDM/phastSim#15]
Dear authors,
I've just found that the option "--rootGenomeLength" doesn't work on phastSim 0.0.3 while it still works well on version 0.0.2.

**- Input files:**

+ tree.nwk
`((((L01:1.25189e-05,(L06:0,L10:0):1.25189e-05):1.77407e-05,L04:3.02596e-05):1.95484e-06,(L03:2.40733e-05,L05:2.40733e-05):8.14108e-06):2.51284e-05,(L02:9.33487e-06,(L07:3.86732e-06,(L08:3.50865e-06,L09:3.50865e-06):3.58672e-07):5.46755e-06):4.8008e-05);`
+ [MN908947.3.fasta](https://raw.githubusercontent.com/NicolaDM/phastSim/main/phastSim/example/MN908947.3.fasta)

**- Command:**

`phastSim --outpath . --seed 1 --treeFile tree.nwk --reference MN908947.3.fasta --outputFile output --rootGenomeLength 1000`

**- Error:**

```
rootGenomeFrequencies = self.init_insertion_frequencies()
TypeError: init_insertion_frequencies() missing 1 required positional argument: 'ref'
```

Could you please help me to check it? Many thanks.

Cheers,
Nhan

**Comment by trongnhanuit** [comment]
I can confirm that the option "--rootGenomeLength" works well on the new version of phastSim (0.0.4). I've just tested it. 

Best regards,
Nhan
